export const HOLD_DRAW_REPEAT_BET = "HOLD_DRAW_REPEAT_BET";
export const TOGGLE_BET = "TOGGLE_BET";
export const HOLD_DRAW_FLIP = "FLIP";
export const HOLD_DRAW_ADD_WINNINGS = "Hold_DRAW_ADD_WINNINGS";
