export const TRIPLE_SEVEN = 'TRIPLE_SEVEN';
export const SEVEN = 'SEVEN';
export const CROWN = 'CROWN';
export const DOUBLE_BAR = 'DOUBLE_BAR';
export const COIN = 'COIN';
export const DOUBLE_HEART = 'DOUBLE_HEART';
export const BAR = 'BAR';
export const CHERRY = 'CHERRY';
export const HEART = 'HEART';
export const WILD = 'WILD';
export const JACKPOT = 'JACKPOT';
export const BONUS = 'BONUS';

export const CARDS = [TRIPLE_SEVEN, SEVEN, CROWN, DOUBLE_BAR, COIN,
                        DOUBLE_HEART, BAR, CHERRY, HEART, JACKPOT, BONUS];


export const HOLD_AND_DRAW_DECK = [TRIPLE_SEVEN, TRIPLE_SEVEN, TRIPLE_SEVEN,
    SEVEN, SEVEN, SEVEN, SEVEN,
    CROWN, CROWN, CROWN, CROWN,
    DOUBLE_BAR, DOUBLE_BAR, DOUBLE_BAR, DOUBLE_BAR,
    COIN, COIN, COIN, COIN, COIN, COIN,
    DOUBLE_HEART, DOUBLE_HEART, DOUBLE_HEART, DOUBLE_HEART, DOUBLE_HEART, DOUBLE_HEART,
    BAR, BAR, BAR, BAR, BAR, BAR, BAR,
    CHERRY, CHERRY, CHERRY, CHERRY, CHERRY, CHERRY, CHERRY,
    HEART, HEART, HEART, HEART, HEART, HEART, HEART, HEART,
];

export const HOLD_AND_DRAW_BIG_DECK = [TRIPLE_SEVEN, TRIPLE_SEVEN, TRIPLE_SEVEN,
    SEVEN, SEVEN, SEVEN, SEVEN,
    CROWN, CROWN, CROWN, CROWN,
    DOUBLE_BAR, DOUBLE_BAR, DOUBLE_BAR, DOUBLE_BAR,
    COIN, COIN, COIN, COIN, COIN, COIN,
    DOUBLE_HEART, DOUBLE_HEART, DOUBLE_HEART, DOUBLE_HEART, DOUBLE_HEART, DOUBLE_HEART,
    BAR, BAR, BAR, BAR, BAR, BAR, BAR,
    CHERRY, CHERRY, CHERRY, CHERRY, CHERRY, CHERRY, CHERRY,
    HEART, HEART, HEART, HEART, HEART, HEART, HEART, HEART,
    WILD,
];

